### ISSUE TITLE
New OSS: crossplatform_mGWAS

### ISSUE THREAD

**Issue by susheel** [HDRUK/oss#5]
```
- name: crossplatform_mGWAS
  url: https://github.com/MRC-Epid/crossplatform_mGWAS
  description: |
    Cross-platform genetic discovery of small molecule products of metabolism and application to clinical outcomes
  keywords:
  - GWAS
  - Metabolism
  categories:
  - Bioinformatics
```
